### ISSUE TITLE
Cmake bracket arguments are not supported

### ISSUE THREAD

**Issue by Lectem** [DaelDe/cmake_check#28] opened 2018-09-15 16:00 UTC
I am getting the following error:

`error: CMakeLists.txt:117 Expected "]" or any character but end of input found.`

Probably because of the following cmake code `set(DOXYGEN_PREDEFINED FORCE_DOXYGEN [[TYPE_TO_STRING(x)=""]])`

Cf. https://cmake.org/cmake/help/latest/manual/cmake-language.7.html#bracket-argument
 for the language feature description.

**Comment by DaelDe** [comment] 2018-09-15 19:12
Thanks for reporting. I will have a look into that.

**Comment by DaelDe** [comment] 2018-09-15 19:47
Analysis: bracket arguments can contain equal signs [==[ but they are also valid without equal signs. In the given example, the text between the brackets contains an equal sign which confused the parser. 
This can be easily fixed in the grammar.

**Closed** 2018-09-16 19:13 UTC
Labels: bug

**Comment by DaelDe** [comment] 2018-09-18 05:04
@Lectem the issue is fixed in 0.2.0 . Please let me know when you get more parser errors. Everything worked fine in my tests.
